//app_action
export const TOGGLE_COMPACT_MODE = "TOGGLE_COMPACT_MODE";
export const ADD_CALENDAR_EVENT = "ADD_CALENDAR_EVENT";
export const DEL_CALENDAR_EVENT = "DEL_CALENDAR_EVENT";
export const SET_OVERLAY = "SET_OVERLAY";
//auth_action
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

//file_action
export const CLEAR_FILE_STATE = "CLEAR_FILE_STATE";
export const DECRYPT_IN_PROGRESS = "DECRYPT_IN_PROGRESS";
export const DECRYPT_ERROR = "DECRYPT_ERROR";
export const DECRYPT_SUCCESS = "DECRYPT_SUCCESS";
export const ENCRYPT_IN_PROGRESS = "ENCRYPT_IN_PROGRESS";
export const ENCRYPT_ERROR = "ENCRYPT_ERROR";
export const ENCRYPT_SUCCESS = "ENCRYPT_SUCCESS";
export const SET_FILE_EXISTS = "SET_FILE_EXISTS";
export const SET_HASHED_PASSWORD = "SET_HASHED_PASSWORD";

//bufl_action
export const SET_BUFL_ELEMENTS = "SET_BUFL_ELEMENTS";

//
export const CLOSE_BANNER_ALERT = "CLOSE_BANNER_ALERT";
export const OPEN_BANNER_ALERT = "OPEN_BANNER_ALERT";
